/** Conditions */
export const conditions = [
  "Blinded",
  "Concen-trating",
  "Charmed",
  "Deafened",
  "Exhausted",
  "Frightened",
  "Grappled",
  "Incapaci-tated",
  "Invisible",
  "Paralyzed",
  "Petrified",
  "Poisoned",
  "Prone",
  "Restrained",
  "Stunned",
  "Un-conscious",
  "Advantage",
  "Baned",
  "Bleeding Out",
  "Blessed",
  "Dis-advantage",
  "Dodge",
  "Flying",
  "Hastened",
  "Hexblade's Curse",
  "Hexed",
  "Holding Action",
  "Hunter's Mark",
  "Inspired",
  "Mage Armor",
  "Raging",
  "Reaction Used",
  "Armor of Agathys",
  "Blink",
  "Blur",
  "Confused",
  "Insightful Fighting",
  "Mirror Image",
  "On Fire",
  "Possessed",
  "Sanctuary",
  "Shield of Faith",
  "Spirit Guardians",
  "Summoning",
  "Symbiotic Entity",
  "Shifted",
  "Truesight",
  "Warding Bond",
  "Ancestral Protectors",
  "Cause of Fear",
  "Compelled Duel",
  "Divine Favor",
  "Highlighted",
  "Slayer's Prey",
  "Stabilized",
  "Shell Defense",
  "Bear's Endurance",
  "Bull's Strength",
  "Cat's Grace",
  "Eagle's Splendor",
  "Fox's Cunning",
  "Owl's Wisdom",
];
