/** Conditions */
export const conditions = [
  "Baned",
  "Blessed",
  "Blinded",
  "Charmed",
  "Concentrating",
  "Deafened",
  "Dodge",
  "Exhausted",
  "Frightened",
  "Grappled",
  "Hastened",
  "Hexed",
  "Holding Action",
  "Hunter's Mark",
  "Incapacitated",
  "Invisible",
  "Paralyzed",
  "Petrified",
  "Poisoned",
  "Prone",
  "Raging",
  "Reaction Used",
  "Restrained",
  "Stunned",
  "Unconscious",
];
